name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: cargo build --verbose
    - name: Download tests
      run: sh ./.github/download_tests.sh
    - name: Run tests
      run: cargo test --verbose
